### ISSUE TITLE
Shopping Cart Feature

### ISSUE THREAD

**Issue by Peilong** [NoahWGeorge/senior-project#1]
Let's push to have this feature by next week. The proposal listed both static and dynamic parts, but the dynamic part is still yet to be started.

**Comment by NoahWGeorge** [comment]
Absolutely.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Peilong Li ***@***.***>
Sent: Tuesday, April 4, 2023 3:06:11 PM
To: NoahWGeorge/senior-project ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NoahWGeorge/senior-project] Shopping Cart Feature (Issue #1)


CAUTION: This message originates from outside the "etown.edu" email system. Please view with care.

Let's push to have this feature by next week. The proposal listed both static and dynamic parts, but the dynamic part is still yet to be started.
